AllCops:
  Exclude:
    - 'bin/**/*'
    - vendor/**/*
    - db/**/* 
    - app/helpers/**/*
    - spec/**/*

Metrics/ClassLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

require:
  - rubocop-capybara
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

MessageSpies:
  Enabled: false