local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

amazon: #TODO: fix it 
service: S3
access_key_id: <%= Rails.application.credentials.dig(:aws, :access_key_id) %>
secret_access_key: <%= Rails.application.credentials.dig(:aws, :secret_access_key) %>
bucket: your_own_bucket-<%= Rails.env %>
region: "" # e.g. 'us-east-1'