dev:
  service: Disk
  root: <%= Rails.root.join("storage") %>

int:
  service: Disk
  root: <%= Rails.root.join("int_storage") %>

amazon: #TODO: fix it 
  service: S3
  access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  bucket: <%= ENV['S3_BUCKET_NAME'] %>
  region: <%= ENV['AWS_Region'] %> # e.g. 'us-east-1'