local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

amazon: #TODO: fix it 
service: S3
access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
bucket: <%= ENV['S3_BUCKET_NAME'] %>
region: "" # e.g. 'us-east-1'