name: "Ruby on Rails CI"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      DATABASE_USERNAME: postgres
      MONEY_APP_ID: ${{ secrets.MONEY_APP_ID }}
      CHROME_USER_DATA_DIR: ./chrome_storage
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # Add or replace dependency steps here
      - name: Install Ruby
        uses: ruby/setup-ruby@78c01b705fd9d5ad960d432d3a0cfa341d50e410 # v1.179.1
        with:
          ruby-version: '3.0.7'
          rubygems: 3.5.23
          bundler-cache: true
      # Add or replace database setup steps here - name: Set up database schema
      - name: download chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 131 # DO NOT TOUCH!!!! THANKS!
          install-chromedriver: true
      - name: create db
        run: bin/rake db:create
      - name: migrate db
        run: bin/rake db:migrate
      - name: seed db
        run: bin/rake db:seed
      # Add or replace test runners here
      - name: Run unit tests
        run: bin/bundle exec rspec
      - name: make image storage dir
        run: mkdir int_storage
      - name: make chrome storage dir
        run: mkdir chrome_storage
      - name: which chrome
        run: which chrome
      - name: Run integration tests
        run: bin/bundle exec cucumber

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@78c01b705fd9d5ad960d432d3a0cfa341d50e410 # v1.179.1
        with:
          ruby-version: '3.0.7'
          rubygems: 3.5.23
          bundler-cache: true
      - name: Lint Ruby files
        run: bin/bundle exec rubocop --parallel