# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "Ruby on Rails CI"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
    steps:
      - name: Install sqlite
        run: sudo apt install sqlite3  
      - name: Checkout code
        uses: actions/checkout@v4
      # Add or replace dependency steps here
      - name: Install Ruby
        uses: ruby/setup-ruby@78c01b705fd9d5ad960d432d3a0cfa341d50e410 # v1.179.1
        with:
          ruby-version: '3.0.0'
          bundler-cache: true
      # DO NOT REMOVE OR WORKFLOW WILL FAIL
      - name: update rubygems
        run: gem update --system 3.5.23 
      # Add or replace database setup steps here - name: Set up database schema
      - name: load db
        run: bin/rake db:schema:load
      # Add or replace test runners here
      - name: Run unit tests
        run: bin/bundle exec rspec
      - name: Run integration tests
        run: bin/bundle exec cucumber

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@78c01b705fd9d5ad960d432d3a0cfa341d50e410 # v1.179.1
        with:
          ruby-version: '3.0.0'
          bundler-cache: true
      # DO NOT REMOVE OR WORKFLOW WILL FAIL
      - name: update rubygems
        run: gem update --system 3.5.23 
      - name: Lint Ruby files
        run: bin/bundle exec rubocop --parallel
